# Generated by Django 3.1.1 on 2021-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_handler',
            fields=[
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('watermark_name', models.CharField(max_length=50)),
                ('user_image', models.ImageField(upload_to='user_image/user_image.jpg')),
            ],
        ),
    ]
